Repository Automattic/WP-Job-Manager, pull requests merged in 2018-06, with the labels that each got.

#1512 Fix: Undefined index in class-wp-job-manager-cpt.php
  includes/admin/class-wp-job-manager-cpt.php
Labels: [Type] Bug

#1387 Added new filter for job dashboard actions which allows success message
  includes/class-wp-job-manager-shortcodes.php
Labels: [Status] Needs Author Reply, [Type] Enhancement

#1493 Check if `wp_job_manager_create_account` exists
  wp-job-manager-functions.php
Labels: [Type] Bug

#1491 Use strict sanitization for usernames
  wp-job-manager-functions.php
Labels: [Type] Bug

#1509 Add option to show logo in Recent Jobs widget
  assets/css/frontend.css
  assets/css/job-listings.css
  assets/css/job-listings.less
  includes/class-wp-job-manager-widget.php
  includes/widgets/class-wp-job-manager-widget-recent-jobs.php
  templates/content-widget-job_listing.php
Labels: [Type] Enhancement

#1525 Fix npm audit errors
  languages/wp-job-manager.pot
  package.json
Labels: [Status] Accepted, [Type] Maintenance

#1532 Don't escape sign in template message entirely of HTML
  templates/account-signin.php
Labels: [Type] Bug
