Repository Automattic/WP-Job-Manager, pull requests merged in 2018-04, with the labels that each got.

#1414 Minor string change for signin template
  templates/account-signin.php
Labels: [Type] Bug

#1422 Adds core email notification handling
  includes/abstracts/abstract-wp-job-manager-email-template.php
  includes/abstracts/abstract-wp-job-manager-email.php
  includes/class-wp-job-manager-email-notifications.php
  includes/emails/class-wp-job-manager-email-admin-new-job.php
  includes/forms/class-wp-job-manager-form-submit-job.php
  templates/emails/admin-notice-new-listing.php
  templates/emails/plain/admin-notice-new-listing.php
  tests/php/includes/stubs/class-wp-job-manager-email-invalid.php
  tests/php/includes/stubs/class-wp-job-manager-email-template-valid.php
  tests/php/includes/stubs/class-wp-job-manager-email-valid.php
  tests/php/includes/stubs/plain-test-template.php
  tests/php/includes/stubs/test-template.php
  tests/php/tests/includes/abstracts/test_class.wp-job-manager-email-template.php
  tests/php/tests/includes/abstracts/test_class.wp-job-manager-email.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
  wp-job-manager.php
Labels: Feature, [Type] Enhancement

#1390 Enqueue the datepicker UI when using a date field in the front-end
  includes/admin/class-wp-job-manager-admin.php
  templates/form-fields/date-field.php
  wp-job-manager.php
Labels: [Type] Bug

#1436 Add email styles and header and footer
  includes/class-wp-job-manager-email-notifications.php
  lib/emogrifier/class-emogrifier.php
  templates/emails/email-footer.php
  templates/emails/email-header.php
  templates/emails/email-styles.php
  templates/emails/plain/email-footer.php
  templates/emails/plain/email-header.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
Labels: [Type] Enhancement

#1440 Add ability to have hidden settings fields in WP admin
  includes/admin/class-wp-job-manager-settings.php
Labels: [Type] Enhancement

#1441 Keep the currently active settings page
  includes/admin/class-wp-job-manager-settings.php
Labels: [Type] Enhancement

#1434 Add basic job details to email notifications
  includes/class-wp-job-manager-email-notifications.php
  templates/emails/admin-notice-new-listing.php
  templates/emails/email-job-details.php
  templates/emails/email-styles.php
  templates/emails/plain/admin-notice-new-listing.php
  templates/emails/plain/email-job-details.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
  wp-job-manager-template.php
Labels: [Type] Enhancement

#1442 Hide WPJM page options for non default languages.
  includes/3rd-party/wpml.php
Labels: [Status] Accepted, [Type] Enhancement

#1438 Notify administrator when employer updates job listing
  includes/class-wp-job-manager-email-notifications.php
  includes/emails/class-wp-job-manager-email-admin-updated-job.php
  includes/forms/class-wp-job-manager-form-edit-job.php
  templates/emails/admin-notice-updated-listing.php
  templates/emails/plain/admin-notice-updated-listing.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
Labels: [Type] Enhancement

#1445 Pre-fill widget instance array with defaults
  includes/class-wp-job-manager-widget.php
  includes/widgets/class-wp-job-manager-widget-featured-jobs.php
  includes/widgets/class-wp-job-manager-widget-recent-jobs.php
Labels: [Type] Bug

#1448 Add settings UI for email notifications
  assets/css/admin.css
  assets/css/admin.less
  includes/abstracts/abstract-wp-job-manager-email-template.php
  includes/abstracts/abstract-wp-job-manager-email.php
  includes/admin/class-wp-job-manager-settings.php
  includes/class-wp-job-manager-data-cleaner.php
  includes/class-wp-job-manager-email-notifications.php
  includes/emails/class-wp-job-manager-email-admin-new-job.php
  includes/emails/class-wp-job-manager-email-admin-updated-job.php
  includes/forms/class-wp-job-manager-form-edit-job.php
  includes/forms/class-wp-job-manager-form-submit-job.php
  tests/php/includes/stubs/class-wp-job-manager-email-invalid.php
  tests/php/includes/stubs/class-wp-job-manager-email-valid.php
  tests/php/tests/includes/abstracts/test_class.wp-job-manager-email-template.php
  tests/php/tests/includes/abstracts/test_class.wp-job-manager-email.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
Labels: [Type] Enhancement

#1453 Update `get_terms()` calls for new format
  includes/admin/class-wp-job-manager-cpt.php
  includes/admin/class-wp-job-manager-writepanels.php
  includes/class-wp-job-manager-usage-tracking-data.php
  templates/job-filters.php
  tests/php/tests/includes/test_class.wp-job-manager-category-walker.php
  wp-job-manager-functions.php
Labels: [Type] Enhancement

#1410 Bump minimum version of WordPress to 4.7
  includes/admin/class-wp-job-manager-admin.php
  readme.md
  readme.txt
  wp-job-manager.php
Labels: [Type] Maintenance

#1454 Add email notification to administrators when a job listing is expiring
  includes/class-wp-job-manager-data-cleaner.php
  includes/class-wp-job-manager-email-notifications.php
  includes/emails/class-wp-job-manager-email-admin-expiring-job.php
  templates/emails/admin-expiring-job.php
  templates/emails/plain/admin-expiring-job.php
Labels: [Type] Enhancement

#1466 Remove email notice cron on uninstall/deactivation
  includes/class-wp-job-manager-data-cleaner.php
  wp-job-manager.php
Labels: [Type] Bug

#1468 Hook new/updated job email notifications to their action hooks
  includes/class-wp-job-manager-email-notifications.php
  includes/forms/class-wp-job-manager-form-edit-job.php
  includes/forms/class-wp-job-manager-form-submit-job.php
Labels: [Type] Enhancement

#1469 Emails should have contexts and use template paths for their context
  includes/abstracts/abstract-wp-job-manager-email-template.php
  includes/abstracts/abstract-wp-job-manager-email.php
  includes/class-wp-job-manager-email-notifications.php
  tests/php/tests/includes/abstracts/test_class.wp-job-manager-email-template.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
Labels: [Type] Enhancement

#1470 Point admins to WP admin for expiring job notices
  templates/emails/admin-expiring-job.php
  templates/emails/plain/admin-expiring-job.php
Labels: [Type] Bug
