Repository Automattic/WP-Job-Manager, pull requests merged in 2019-05, with the labels that each got.

#1730 Removes Mixtape and custom REST API
  Gruntfile.js
  includes/rest-api/class-wp-job-manager-controllers-status.php
  includes/rest-api/class-wp-job-manager-data-stores-status.php
  includes/rest-api/class-wp-job-manager-filters-status.php
  includes/rest-api/class-wp-job-manager-models-job-categories-custom-fields.php
  includes/rest-api/class-wp-job-manager-models-job-listings-custom-fields.php
  includes/rest-api/class-wp-job-manager-models-job-types-custom-fields.php
  includes/rest-api/class-wp-job-manager-models-settings.php
  includes/rest-api/class-wp-job-manager-models-status.php
  includes/rest-api/class-wp-job-manager-registrable-job-categories.php
  includes/rest-api/class-wp-job-manager-registrable-job-listings.php
  includes/rest-api/class-wp-job-manager-registrable-job-types.php
  includes/rest-api/class-wp-job-manager-registrable-taxonomy-type.php
  includes/rest-api/class-wp-job-manager-rest-api.php
  mixtape.json
  package-lock.json
  package.json
  tests/bin/run-travis.sh
  wp-job-manager.php
Labels: Deprecation

#1739 Track job submission and approval events
  includes/class-wp-job-manager-post-types.php
  includes/class-wp-job-manager-usage-tracking-data.php
  includes/class-wp-job-manager-usage-tracking.php
  includes/forms/class-wp-job-manager-form-submit-job.php
Labels: Usage Tracking

#1752 Add event tracking for extensions and license activation
  includes/class-wp-job-manager-usage-tracking-data.php
  includes/class-wp-job-manager-usage-tracking.php
  includes/class-wp-job-manager.php
  includes/helper/class-wp-job-manager-helper.php
  lib/usage-tracking/class-usage-tracking-base.php
  tests/php/tests/includes/test_class.wp-job-manager-usage-tracking-data.php
Labels: Usage Tracking

#1743 Change how `[jobs]` maintains state when navigating away and refreshing
  assets/js/ajax-filters.js
  assets/js/ajax-filters.min.js
  includes/class-wp-job-manager-ajax.php
Labels: [Type] Bug

#1732 Job Submission Form: Validate Description and Category Fields Client Side
  assets/js/job-submission.js
  assets/js/job-submission.min.js
  includes/class-wp-job-manager.php
Labels: [Pri] Low, [Type] Enhancement

#1759 Create a more unique cache storage key per `[jobs]` instance
  assets/js/ajax-filters.js
  assets/js/ajax-filters.min.js
  includes/class-wp-job-manager-shortcodes.php
Labels: [Type] Bug
