Repository Automattic/WP-Job-Manager, pull requests merged in 2019-09, with the labels that each got.

#1805 Try not to preserve form on refresh
  assets/js/ajax-filters.js
  assets/js/ajax-filters.min.js
Labels: [Status] Proposal

#1807 Clear filled flag when relisting
  includes/forms/class-wp-job-manager-form-submit-job.php
Labels: [Type] Bug

#1871 Add author to the job listing post type "supports".
  includes/class-wp-job-manager-post-types.php
Labels: [Pri] Low, [Type] Enhancement

#1850 Fix: Two options aren't deleted when plugin is uninstalled.
  includes/class-wp-job-manager-data-cleaner.php
Labels: [Type] Bug

#1868 Conditionally use https on Google Maps link.
  wp-job-manager-template.php
Labels: [Type] Bug

#1852 Fix #1465 Menu Position of the Job Listings Custom Post Type
  includes/class-wp-job-manager-post-types.php
Labels: [Pri] Low

#1876 Revert removal of direct database access in two places
  includes/admin/class-wp-job-manager-writepanels.php
  includes/class-wp-job-manager-post-types.php
Labels: [Type] Bug

#1887 Just return cached results when the fields arg is `id=>parent`
  wp-job-manager-functions.php
Labels: [Type] Bug

#1886 Properly format file extensions that were separated by pipes in upload error message
  wp-job-manager-functions.php
Labels: [Type] Bug

#1883 Allow using term slugs for preselecting category filter
  includes/class-wp-job-manager-shortcodes.php
Labels: [Type] Enhancement
