Repository Automattic/WP-Job-Manager, pull requests merged in 2020-12, with the labels that each got.

#2079 Fix jobs list not appearing in the page load while using Firefox
  assets/js/ajax-filters.js
Labels: [Type] Bug

#2081 Release 1.34.5
  changelog.txt
  languages/wp-job-manager.pot
  package-lock.json
  package.json
  readme.txt
  wp-job-manager.php
Labels: [Type] Maintenance

#2082 Revert "Release 1.34.5"
  changelog.txt
  languages/wp-job-manager.pot
  package-lock.json
  package.json
  readme.txt
  wp-job-manager.php
Labels: [Type] Maintenance

#2085 Release 1.34.5
  assets/js/ajax-filters.js
  assets/js/ajax-filters.min.js
  changelog.txt
  languages/wp-job-manager.pot
  package-lock.json
  package.json
  readme.md
  readme.txt
  wp-job-manager.php
Labels: [Type] Maintenance

#2084 Revert "Release 1.34.5"
  changelog.txt
  languages/wp-job-manager.pot
  package-lock.json
  package.json
  readme.txt
  wp-job-manager.php
Labels: [Type] Maintenance

#2087 Release 1.34 merge - master
  changelog.txt
  languages/wp-job-manager.pot
  package-lock.json
  package.json
  readme.txt
  wp-job-manager.php
Labels: [Type] Maintenance

#2090 Add job_manager_get_form_action filter fixes #2089
  includes/abstracts/abstract-wp-job-manager-form.php
Labels: Hooks
