Repository Automattic/WP-Job-Manager, pull requests merged in 2023-04, with the labels that each got.

#2388 Use ubuntu latest
  .github/workflows/build.yml
  .github/workflows/php.yml
  .github/workflows/report-build.yml
Labels: [Type] Maintenance

#2380 Add/email notification settings
  includes/class-wp-job-manager-email-notifications.php
  includes/emails/class-wp-job-manager-email-admin-expiring-job.php
  includes/emails/class-wp-job-manager-email-admin-new-job.php
  includes/emails/class-wp-job-manager-email-admin-updated-job.php
  tests/php/tests/includes/test_class.wp-job-manager-email-notifications.php
Labels: [Status] Needs Documentation

#2400 Design Adjustments for the Licenses page for WPJM addons
  assets/css/admin.scss
  assets/images/icons/checkmark-icon.svg
  includes/helper/views/html-licences.php
Labels: [Type] Enhancement, Re-engaging Customers
