Repository Automattic/WP-Job-Manager, pull requests merged in 2023-11, with the labels that each got.

#2631 Safeguard array in WP_Job_Manager_Settings::input_capabilities
  composer.json
  composer.lock
  includes/admin/class-wp-job-manager-settings.php
  tests/php/includes/stubs/class-wp-job-manager-admin-settings-stub.php
  tests/php/tests/includes/admin/test_class.wp-job-manager-settings.php
Labels: [Type] Bug, [Pri] Normal, Customer Report

#2607 Update readme text
  readme.txt
  scripts/create-release.mjs
Labels: [Type] Maintenance

#2646 Small fixes to actions and release script
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/gardening.yml
  .github/workflows/github-pages.yml
  .github/workflows/php.yml
  .github/workflows/release-checklist.yml
  .github/workflows/report-build.yml
  scripts/prepare-release.mjs
Labels: [Type] Maintenance

#2651 Improve upsell styles so it is less distracting
  assets/css/admin.scss
  assets/css/menu.scss
  includes/admin/class-wp-job-manager-addons-landing-page.php
Labels: [Type] Enhancement
